spring.application.name=masterchef-api
spring.data.mongodb.uri=mongodb+srv://adminMaster:<admin>@masterchefcluster.51rh5au.mongodb.net/?retryWrites=true&w=majority&appName=MasterChefCluster
server.port=8080

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html 